volumes:
  shortener_volume:

services:
  shortener:
    image: alirn76/url-shortener:latest
    restart: always
    ports:
      - 8000:8000
    volumes:
      - shortener:/shortener/database
    environment:
      WORKER: 1
      PRIVATE: true
      BASE_URL: "https://example.com"
      TITLE: "Simple URL Shortener"
      DESCRIPTION: Create Short & Memorable URL In a Seconds."
